name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build artifact
      run: zip mackerel-plugin-dice.zip mackerel-plugin-dice README.md LICENSE
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref_name }}
        artifacts: mackerel-plugin-dice.zip
